name: Deploy ChatBot Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Backend Dependencies
      run: |
        cd chatbot-backend
        npm ci
    
    - name: Install Frontend Dependencies
      run: |
        cd chatbot-frontend
        npm ci
    
    - name: Build Frontend
      run: |
        cd chatbot-frontend
        npm run build
    
    - name: Run Backend Tests
      run: |
        cd chatbot-backend
        npm test
      env:
        CI: true